#! /bin/sh

export PATH="$HOME/.local/bin:$PATH"

# Restore wallpaper
variety --resume &

# Start keybindings daemon
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc &

#Start polybar
$HOME/.config/bspwm/polybar/launch.sh

bspc monitor -d      ﲵ אַ ﭧ  

bspc config border_width         1
bspc config window_gap           15
bspc config split_ratio          0.50

bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color  "#32344a"
bspc config active_border_color  "#444b6a"

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle        false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name phinger-cursors &

# The minimum interval, in milliseconds, between two motion notify events.
bspc config pointer_motion_interval 7

# Floating Wndows
declare -a floats=(Alafloat
                   Lxappearance
                   Arandr
                   Timeshift-gtk
                   Viewnior
                   feh
                   Nm-connection-editor
                   Matplotlib
                   Yad
                   Nitrogen
                   GParted
                   Pavucontrol
                   qt5ct)
    for i in ${floats[@]}; do
        bspc rule -a $i state=floating follow=on focus=on; done

# Windows
bspc rule -a scpad sticky=on state=floating focus=on
bspc rule -a Emacs state=tiled focus=on follow=on
bspc rule -a spot sticky=on state=floating focus=on rectangle=800x400+1280+330
bspc rule -a fluent-reader state=pseudo_tiled focus=on follow=on rectangle=1699x1363+10-10


## Autostart

# Set bsp layouts
bsp-layout set tiled  &
bsp-layout set tiled  &
bsp-layout set tiled  &
bsp-layout set tiled  &
bsp-layout set tiled  &
bsp-layout set tiled ﭧ &
bsp-layout set tiled אַ &
bsp-layout set tiled ﲵ &
bsp-layout set tiled  &
bsp-layout set tiled  &

# Kill if already running
killall -9 blueberry-tray picom dunst ksuperkey xidlehook alttab glava kdeconnect-indicator indicator-keylock xfce4-power-manager caffeine

# Start blueberry-tray
blueberry-tray &

# Start xidlehook for lock screen
xidlehook --not-when-fullscreen --not-when-audio --timer 600 'lock' '' &

# Launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/bspwm/picom.conf &

# Change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal"
cp "$XFCE_TERM_PATH"/colorschemes/tokyo-night "$XFCE_TERM_PATH"/terminalrc

# Change cava colorscheme
CAVA_PATH="$HOME/.config/cava"
cp "$CAVA_PATH"/colorschemes/tokyo-night "$CAVA_PATH"/config

# Start window Switcher
def-alttab &

# Start emacs deamon
emacs -daemon &

# Start openrgb
pgrep -x openrgb > /dev/null || openrgb -p cyber.orp &

# Start Keylock indicator
indicator-keylock &

# Start power manager
xfce4-power-manager &

# Start caffeine
caffeine &

# Start kdeconnect-indicator
# sh -c 'sleep 15 && kdeconnect-indicator &'

# Start glava
# sh -c 'sleep 10 && glava --desktop'

# Launch Conkeww
# sed -i "s/colors\/color-.*/colors\/color-tokyo.yuck\")/g" $HOME/.config/conkeww/eww.yuck
# eww --config $HOME/.config/conkeww/ open conkeww-main

# Start numlockx
# numlockx &

# Enable Super Keys For Menu
#ksuperkey -e 'Super_L=Alt_L|F1' &
#ksuperkey -e 'Super_R=Alt_L|F1' &
